mongodbDatabase: exampleDb
mongodbUri: "mongodb://127.0.0.1:27017"
apiPort: 9898
server:
  port: 8080
smpp:
  host: localhost
  port: 2775
  systemId: smppclient1
  password: password

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
